### PR TITLE
Un-fixing nav on desktop 

### PR DESCRIPTION
**Pull request by jasonbelmonti**
added margin to line numbers where code snippets are highlighted by coderay

fixed helper API page issue with nested <ul> tags (+1 squashed commit)
Squashed commits:
[c501954] Un-fixing nav on desktop

### CODE REVIEW

**Comment by smfoote** [comment]
Can you do a `git pull --rebase` from the LinkedIn fork, then push the result. Also, could you attach some screenshots?

**Comment by sethkinast** [comment]
Changes look good to me. We can't merge until you pull and rebase.

When you rebase and squash, make sure you click "Edit Message" on the SourceTree squash window and remove all the cruft about "+3 squashed commits" etc. Clean commit log :)

**Comment by sethkinast** [comment]
Code highlighting works in fenced blocks.

Also notice when scrolling the menu isn't fixed anymore so we can add more stuff.

screen shot 2015-03-24 at 10 14 43 am
screen shot 2015-03-24 at 10 14 21 am

**Comment by smfoote** [comment]
Thanks Jason!

**Pull request merged**
