### PR TITLE
Bug with whitespace: true & leading spaces in partial block.

### PR DESCRIPTION
**Pull request by BradEstey**
Writing something like this with `dust.config = { whitespace: true }`

```dustjs
<section>{+body/}</section>
{<body}
    <h1>Title</h1>
    <p>Content...</p>
{/body}
```

Would render as: 
```dustjs
<section>
<h1>Title</h1>
    <p>Content...</p>    
</section>
```

This pull request adds a failing test for this edge case and fixes it to return this instead:
```dustjs
<section>
    <h1>Title</h1>
    <p>Content...</p>    
</section>
```

I've also added a few other whitespace related tests. I'm not sure if it had much coverage before.

### CODE REVIEW

**Comment by sethkinast** [comment]
Thanks for the PR and especially the test coverage!

To save me some context switching, can you explain the compiler change? Why is memo[2] needed?

**Comment by sethkinast** [comment]
You can use `grunt test` to run the full test suite (what Travis runs) to make sure it passes.

Please rebase and squash after you've done that.

**Comment by BradEstey** [comment]
Tests should be fixed now. I didn't have Java installed so was only running `grunt jasmine`. 

So the basic idea is that if there are multiple pieces of formatting prior to a buffer then only the first one is used. So `[ 'format', '\n', '    ', [ 'line', 7 ], [ 'col', 76 ] ][ 'buffer', '</p>', [ 'line', 8 ], [ 'col', 5 ] ]` would collapse down to `\n</p>` instead of `\n    </p>` due to this line:

```javascript
memo[1] += res.slice(1, -2).join('');
```

Which is fine, because the formatting didn't matter before. But, now with the `dust.config.whitespace` options, every piece of formatting needs to be retained. Only if whitespace is true though, so I added a conditional. I've removed the` memo[2]` because it was ugly and I wasn't sure if there would ever be more than 5 items in an array. That was only there to peal out any formatting between the first two items and the last two items. Now I'm using this to peal out all the items between the first and last two items and combine them:

```javascript
if (dust.config.whitespace && memo.length > 4) {
    memo.splice(1, memo.length - 3, memo.slice(1, -2).join(''));
}
```

Otherwise, the 3rd item would keep getting retained and repeated.

**Comment by sethkinast** [comment]
Thanks for the update. I remember this now-- it was caused by keeping the grammar unchanged after my whitespace changes.

    buffer "buffer"
      = e:eol w:ws*
      { return ["format", e, w.join('')].concat([['line', line()], ['col', column()]]) }

I had initially rewritten the grammar to join these together.

`format` node collections are the only buffer-style collections with this special concept of two nodes after the identifier.

Could we add this logic into the `format` optimizer to keep the `compactBuffers` logic as simple as possible? Around line 143 of `compiler.js`: 

    function format(context, node) {
      if(dust.config.whitespace) {
        node.splice(1, 2, node.slice(1, -2).join(''));
        return node;
      }
      return null;
    }

Tests look great. Would you update their messages slightly for the ones that have `whitespace = true` so that you can tell from the test overview that whitespace is intentionally preserved? And finally, if you could explicitly specify `whitespace: false` on the others so that if the default behavior changes, the tests still pass.

Those changes plus a squash = :+1: here, one more set of eyes will be good.

**Comment by prashn64** [comment]
Agree with Seth but can you comment your intention when you make that change?  It was confusing without the explanation.

Thanks a ton for those tests btw.

**Comment by jimmyhchan** [comment]
:+1:  Thanks for this! Good work. Looks good.

Summarizing the comments above
- [ ] add this to `format` optimizer instead
- [ ] update message in tests where `whitespace = true` to explain that whitespace is intentionally preserved
- [ ] update remaining tests to `whitespace = false` so tests won't fail if the default config changes
- [ ] add a code comment explaining the `splice ... slice` line as you had here
- [ ] squash commits

**Comment by sethkinast** [comment]
Looks like Brad went quiet so I've modified his branch, squashed, and pushed (leaving author attribution intact).

Thanks for the PR!

**Pull request closed without merging**
