### PR TITLE
Add AMD (require.js) compatibility.

### PR DESCRIPTION
**Pull request by sethkinast**

### CODE REVIEW

**Comment by rragan** [comment]
lgtm

**Comment by sethkinast** [comment]
After talking offline with @jimmyhchan I updated the support to hide AMD support behind a flag, in the same way that jQuery does.

Setting `define.amd.dust` to `true` will enable AMD support. This will prevent people from being broken if they have an AMD loader but assume Dust is a global (aka LinkedIn wheeeee).

In a future release we can adjust the default behavior to an opt-out.

**Comment by sethkinast** [comment]
Wiki: https://github.com/linkedin/dustjs/wiki/Loading-Dust-via-AMD-(require.js)

**Comment by kyhy** [comment]
Looking forward to this update!

Would this change also effect dustc?

**Comment by sethkinast** [comment]
dustc is the command-line compiler-- it shouldn't have a use case where
it's required via AMD, should it?

On Wed, Jan 28, 2015 at 3:17 PM, kyhy <notifications@github.com> wrote:

> Looking forward to this update!
>
> Would this change also effect dustc?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linkedin/dustjs/pull/536#issuecomment-71937617>.
>



-- 
Seth Kinast
http://sethkinast.com/

**Comment by kyhy** [comment]
I'm pre-compile using dustc and store returned *.js files for faster rendering

I get something along the lines of:
```javascript
 (function(){dust.register("dust-module_simplechart_bar",body_0);function body_0(chk,ctx){return chk.w("<div><div id=\"").f(ctx.get(["chartId"], false),ctx,"h").w("\"></div></div>");}body_0.__dustBody=!0;return body_0;})();
```
ps. I'm using webpack and not requirejs... but I don't think it should make a difference? D:

**Comment by sethkinast** [comment]
I see. Currently this change doesn't account for loading templates via AMD,
just Dust itself.

I will look into it-- it may not hit this release, though.

On Wed, Jan 28, 2015 at 3:53 PM, kyhy <notifications@github.com> wrote:

> I'm pre-compile using dustc and store returned *.js files for faster
> rendering
>
> I get something along the lines of:
>
>  (function(){dust.register("dust-module_simplechart_bar",body_0);function body_0(chk,ctx){return chk.w("<div><div id=\"").f(ctx.get(["chartId"], false),ctx,"h").w("\"></div></div>");}body_0.__dustBody=!0;return body_0;})();
>
> ps. I'm using webpack and not requirejs... but I don't think it should
> make a difference? D:
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linkedin/dustjs/pull/536#issuecomment-71942176>.
>



-- 
Seth Kinast
http://sethkinast.com/

**Comment by sethkinast** [comment]
@kyhy I have some follow up questions about how you use require.js with your templates. If you are using webpack, doesn't it bundle up all the templates into a single file that you include, and then everything is available in the dust cache? Do you keep all the template files separate and dynamically request them one at a time?

**Comment by kyhy** [comment]
I do store all the dust files separate and request them one at a time. For
deploy, I generate a minified template js file.

With webpack, I really struggled trying to shim dust, dust-helpers and the
minified dust template js file. Couldn't find or understand their
documentations.

Additionally, may have worked if I didn't mix up dust 2.4.2 with 2.5.*
version. I used 2.5.* dustc and used 2.4.2 dust-full...

Ended up switching over to requirejs (better api docs). I followed their
intro docs and restructured my modules. Shimming just works with require...

**Comment by sethkinast** [comment]
This has gotten better.

- dust is now an anonymous module, so you can `require(['lib/dust-core'], ...)` or whatever instead of having to set `paths`.
- dust knows how to compile templates as AMD modules. If AMD mode is turned on, Dust will try to `require` templates that aren't in its cache.
- Includes work as normal-- if they aren't cached, Dust will try to `require` them too.

**Comment by sethkinast** [comment]
```        define.amd.dust = true;
        require(["lib/dust-core"], function(dust) {
            require(["lib/dust-helpers", "tmpl/hello"], function() {
                dust.render("tmpl/hello", {"check": 1}, function(err, out) {
                    if(err) console.error(err);
                    document.getElementById('hello').textContent = out;
                });
            });
        });```

**Comment by sethkinast** [comment]
@kyhy Could you take a look at the **Templates** section of https://github.com/linkedin/dustjs/wiki/Loading-Dust-via-AMD-(require.js) and let me know if that's what you would expect Dust to do?

**Comment by kyhy** [comment]
@sethkinast looks pretty straight forward :D thanks!

In terms of helpers.... adding this in the requirej.config might help in loading dust before dust-helpers instead of nesting two requires. This will be useful if you need to return a value and can't nest require/define within one another.
```javascript
requirejs.config({
    paths: {
        'dust': 'dust-full',
        'dust-helpers': 'dust-helpers'
    },
    shim: {
        'dust-helpers': ['dust']
    }
});
```

**Comment by sethkinast** [comment]
Yeah, understood. Implementation can be left as an exercise to the reader ;) not all AMD implementations have shim available.

You can also get around it much more simply by shimming `dust.core` but the suggestion on the wiki is the most generic to make it "just work" I think.

Thanks for taking a look.

**Comment by prashn64** [comment]
lgtm after a squash.  Can we get one more set of eyes @rragan @jimmyhchan

**Pull request merged**
